[en]
languageName = "English"
languagedirection = "ltr"
weight = 1

[en.params.sidebar]
# emoji = "ğŸ¥"
subtitle = "Things I learned during my runtime."

[pt-br]
languageName = "PortuguÃªs"
languagedirection = "ltr"
weight = 2

[pt-br.params.sidebar]
# emoji = "ğŸ¥"
subtitle = "Coisas que aprendi no meu runtime."
